export const educationOptions = [
  "High School",
  "Associate Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate (PhD)",
  "Professional Degree",
  "Trade School",
  "Some College",
  "Other",
]

export const occupationOptions = [
  "Software Engineer",
  "Doctor",
  "Teacher",
  "Nurse",
  "Lawyer",
  "Accountant",
  "Manager",
  "Sales Representative",
  "Marketing Specialist",
  "Designer",
  "Consultant",
  "Engineer",
  "Analyst",
  "Administrator",
  "Technician",
  "Student",
  "Retired",
  "Unemployed",
  "Self-Employed",
  "Other",
]
